name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: jdx/mise-action@v2
      - run: mise run ci
